name: Tests

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  php-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        phpunit-versions: ['10']

    name: P${{ matrix.php }} - PHPUnit ${{ matrix.phpunit-versions }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov
        tools: phpunit:${{ matrix.phpunit-versions }}

    - name: Install dependencies
      run: |
        composer install --prefer-dist

    - name: Execute Unit Tests
      run: composer test